# Generated by Django 3.0.8 on 2020-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=110)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=150)),
                ('smtpserver', models.CharField(max_length=150)),
                ('smptemail', models.CharField(max_length=150)),
                ('smtppassword', models.CharField(max_length=150)),
                ('smtpport', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
                ('aboutus', models.TextField(max_length=150)),
                ('references', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
