# Generated by Django 3.0.8 on 2020-08-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200801_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='note',
            field=models.CharField(max_length=150),
        ),
    ]
