# Generated by Django 3.0.8 on 2020-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200801_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Readed', 'Okundu'), ('Answered', 'Cevaplandı')], default='', max_length=10),
        ),
    ]
