# Generated by Django 3.0.8 on 2020-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200801_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='note',
            field=models.CharField(default='', max_length=150),
        ),
    ]
