# Generated by Django 3.0.8 on 2020-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20200801_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(default='', max_length=200),
        ),
    ]
