# Generated by Django 3.0.8 on 2020-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20200802_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
