# Generated by Django 3.0.8 on 2020-08-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_product_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='services',
        ),
        migrations.AddField(
            model_name='product',
            name='roomtypes',
            field=models.CharField(choices=[('King Room', 'Kral Dairesi'), ('Economic', 'Ekonomik'), ('Balayı', 'Balayı')], default='', max_length=10),
        ),
    ]
