# Generated by Django 3.0.8 on 2020-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20200802_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roomtypes',
            field=models.CharField(default='', max_length=200),
        ),
    ]
