# Generated by Django 3.0.8 on 2020-08-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20200802_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
