# Generated by Django 3.0.8 on 2020-08-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20200802_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
