# Generated by Django 3.0.8 on 2020-08-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20200818_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='odasayisi',
            field=models.IntegerField(default=0),
        ),
    ]
