# Generated by Django 3.0.8 on 2020-08-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200819_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Beklemede', 'Beklemede'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=10),
        ),
    ]
