# Generated by Django 3.0.8 on 2020-08-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Beklemede', 'Beklemede'), ('Reddedildi', 'Reddedildi'), ('Tarih Sonlandı', 'Tarih Sonlandı')], default='Beklemede', max_length=20),
        ),
    ]
